/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package mosaic.interop.idl.kvstore;

@SuppressWarnings("all")
public class OperationResponse extends
		org.apache.avro.specific.SpecificRecordBase implements
		org.apache.avro.specific.SpecificRecord {
	public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema
			.parse("{\"type\":\"record\",\"name\":\"OperationResponse\",\"namespace\":\"mosaic.interop.idl.kvstore\",\"fields\":[{\"name\":\"token\",\"type\":{\"type\":\"record\",\"name\":\"CompletionToken\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"client_id\",\"type\":\"string\"}]}},{\"name\":\"name\",\"type\":{\"type\":\"enum\",\"name\":\"OperationNames\",\"symbols\":[\"SET\",\"ADD\",\"REPLACE\",\"APPEND\",\"PREPEND\",\"CAS\",\"GET\",\"GET_BULK\",\"DELETE\",\"LIST\"]}},{\"name\":\"is_error\",\"type\":\"boolean\"},{\"name\":\"response\",\"type\":[{\"type\":\"error\",\"name\":\"MemcachedError\",\"fields\":[{\"name\":\"explanation\",\"type\":\"string\"}]},\"boolean\",{\"type\":\"map\",\"values\":\"bytes\"},{\"type\":\"array\",\"items\":\"string\"}]}]}");
	public mosaic.interop.idl.kvstore.CompletionToken token;
	public mosaic.interop.idl.kvstore.OperationNames name;
	public boolean is_error;
	public java.lang.Object response;

	public org.apache.avro.Schema getSchema() {
		return SCHEMA$;
	}

	// Used by DatumWriter. Applications should not call.
	public java.lang.Object get(int field$) {
		switch (field$) {
		case 0:
			return token;
		case 1:
			return name;
		case 2:
			return is_error;
		case 3:
			return response;
		default:
			throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}

	// Used by DatumReader. Applications should not call.
	@SuppressWarnings(value = "unchecked")
	public void put(int field$, java.lang.Object value$) {
		switch (field$) {
		case 0:
			token = (mosaic.interop.idl.kvstore.CompletionToken) value$;
			break;
		case 1:
			name = (mosaic.interop.idl.kvstore.OperationNames) value$;
			break;
		case 2:
			is_error = (java.lang.Boolean) value$;
			break;
		case 3:
			response = (java.lang.Object) value$;
			break;
		default:
			throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}
}
