/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package mosaic.interop.idl.amqp;

@SuppressWarnings("all")
public class GetOperation extends org.apache.avro.specific.SpecificRecordBase
		implements org.apache.avro.specific.SpecificRecord {
	public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema
			.parse("{\"type\":\"record\",\"name\":\"GetOperation\",\"namespace\":\"mosaic.interop.idl.amqp\",\"fields\":[{\"name\":\"queue\",\"type\":\"string\"},{\"name\":\"autoack\",\"type\":\"boolean\"}]}");
	public java.lang.CharSequence queue;
	public boolean autoack;

	public org.apache.avro.Schema getSchema() {
		return SCHEMA$;
	}

	// Used by DatumWriter. Applications should not call.
	public java.lang.Object get(int field$) {
		switch (field$) {
		case 0:
			return queue;
		case 1:
			return autoack;
		default:
			throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}

	// Used by DatumReader. Applications should not call.
	@SuppressWarnings(value = "unchecked")
	public void put(int field$, java.lang.Object value$) {
		switch (field$) {
		case 0:
			queue = (java.lang.CharSequence) value$;
			break;
		case 1:
			autoack = (java.lang.Boolean) value$;
			break;
		default:
			throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}
}
