/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package mosaic.interop.idl.amqp;

@SuppressWarnings("all")
public class PublishOperation extends
		org.apache.avro.specific.SpecificRecordBase implements
		org.apache.avro.specific.SpecificRecord {
	public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema
			.parse("{\"type\":\"record\",\"name\":\"PublishOperation\",\"namespace\":\"mosaic.interop.idl.amqp\",\"fields\":[{\"name\":\"data\",\"type\":\"bytes\"},{\"name\":\"durable\",\"type\":\"boolean\"},{\"name\":\"exchange\",\"type\":\"string\"},{\"name\":\"immediate\",\"type\":\"boolean\"},{\"name\":\"mandatory\",\"type\":\"boolean\"},{\"name\":\"routingKey\",\"type\":\"string\"}]}");
	public java.nio.ByteBuffer data;
	public boolean durable;
	public java.lang.CharSequence exchange;
	public boolean immediate;
	public boolean mandatory;
	public java.lang.CharSequence routingKey;

	public org.apache.avro.Schema getSchema() {
		return SCHEMA$;
	}

	// Used by DatumWriter. Applications should not call.
	public java.lang.Object get(int field$) {
		switch (field$) {
		case 0:
			return data;
		case 1:
			return durable;
		case 2:
			return exchange;
		case 3:
			return immediate;
		case 4:
			return mandatory;
		case 5:
			return routingKey;
		default:
			throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}

	// Used by DatumReader. Applications should not call.
	@SuppressWarnings(value = "unchecked")
	public void put(int field$, java.lang.Object value$) {
		switch (field$) {
		case 0:
			data = (java.nio.ByteBuffer) value$;
			break;
		case 1:
			durable = (java.lang.Boolean) value$;
			break;
		case 2:
			exchange = (java.lang.CharSequence) value$;
			break;
		case 3:
			immediate = (java.lang.Boolean) value$;
			break;
		case 4:
			mandatory = (java.lang.Boolean) value$;
			break;
		case 5:
			routingKey = (java.lang.CharSequence) value$;
			break;
		default:
			throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}
}
