/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package mosaic.interop.idl.kvstore;

@SuppressWarnings("all")
public class Operation extends org.apache.avro.specific.SpecificRecordBase
		implements org.apache.avro.specific.SpecificRecord {
	public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema
			.parse("{\"type\":\"record\",\"name\":\"Operation\",\"namespace\":\"mosaic.interop.idl.kvstore\",\"fields\":[{\"name\":\"operation\",\"type\":[{\"type\":\"record\",\"name\":\"StoreOperation\",\"fields\":[{\"name\":\"token\",\"type\":{\"type\":\"record\",\"name\":\"CompletionToken\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"client_id\",\"type\":\"string\"}]}},{\"name\":\"name\",\"type\":{\"type\":\"enum\",\"name\":\"OperationNames\",\"symbols\":[\"SET\",\"ADD\",\"REPLACE\",\"APPEND\",\"PREPEND\",\"CAS\",\"GET\",\"GET_BULK\",\"DELETE\"]}},{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"exptime\",\"type\":\"int\"},{\"name\":\"data\",\"type\":\"bytes\"}]},{\"type\":\"record\",\"name\":\"GetOperation\",\"fields\":[{\"name\":\"token\",\"type\":\"CompletionToken\"},{\"name\":\"name\",\"type\":\"OperationNames\"},{\"name\":\"keys\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]},{\"type\":\"record\",\"name\":\"DeleteOperation\",\"fields\":[{\"name\":\"token\",\"type\":\"CompletionToken\"},{\"name\":\"name\",\"type\":\"OperationNames\"},{\"name\":\"key\",\"type\":\"string\"}]}]}]}");
	public java.lang.Object operation;

	public org.apache.avro.Schema getSchema() {
		return SCHEMA$;
	}

	// Used by DatumWriter. Applications should not call.
	public java.lang.Object get(int field$) {
		switch (field$) {
		case 0:
			return operation;
		default:
			throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}

	// Used by DatumReader. Applications should not call.
	@SuppressWarnings(value = "unchecked")
	public void put(int field$, java.lang.Object value$) {
		switch (field$) {
		case 0:
			operation = (java.lang.Object) value$;
			break;
		default:
			throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}
}
