/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package mosaic.interop.idl.kvstore;

@SuppressWarnings("all")
public enum OperationNames {
	SET, ADD, REPLACE, APPEND, PREPEND, CAS, GET, GET_BULK, DELETE;
	public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema
			.parse("{\"type\":\"enum\",\"name\":\"OperationNames\",\"namespace\":\"mosaic.interop.idl.kvstore\",\"symbols\":[\"SET\",\"ADD\",\"REPLACE\",\"APPEND\",\"PREPEND\",\"CAS\",\"GET\",\"GET_BULK\",\"DELETE\"]}");
}
