/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package mosaic.interop.idl.amqp;

@SuppressWarnings("all")
public class BindQueueOperation extends
		org.apache.avro.specific.SpecificRecordBase implements
		org.apache.avro.specific.SpecificRecord {
	public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema
			.parse("{\"type\":\"record\",\"name\":\"BindQueueOperation\",\"namespace\":\"mosaic.interop.idl.amqp\",\"fields\":[{\"name\":\"exchange\",\"type\":\"string\"},{\"name\":\"queue\",\"type\":\"string\"},{\"name\":\"routing_key\",\"type\":\"string\"}]}");
	public java.lang.CharSequence exchange;
	public java.lang.CharSequence queue;
	public java.lang.CharSequence routing_key;

	public org.apache.avro.Schema getSchema() {
		return SCHEMA$;
	}

	// Used by DatumWriter. Applications should not call.
	public java.lang.Object get(int field$) {
		switch (field$) {
		case 0:
			return exchange;
		case 1:
			return queue;
		case 2:
			return routing_key;
		default:
			throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}

	// Used by DatumReader. Applications should not call.
	@SuppressWarnings(value = "unchecked")
	public void put(int field$, java.lang.Object value$) {
		switch (field$) {
		case 0:
			exchange = (java.lang.CharSequence) value$;
			break;
		case 1:
			queue = (java.lang.CharSequence) value$;
			break;
		case 2:
			routing_key = (java.lang.CharSequence) value$;
			break;
		default:
			throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}
}
