/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package mosaic.interop.idl.amqp;

@SuppressWarnings("all")
public class ConsumeOperation extends
		org.apache.avro.specific.SpecificRecordBase implements
		org.apache.avro.specific.SpecificRecord {
	public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema
			.parse("{\"type\":\"record\",\"name\":\"ConsumeOperation\",\"namespace\":\"mosaic.interop.idl.amqp\",\"fields\":[{\"name\":\"queue\",\"type\":\"string\"},{\"name\":\"consumer\",\"type\":\"string\"},{\"name\":\"exclusive\",\"type\":\"boolean\"},{\"name\":\"autoack\",\"type\":\"boolean\"},{\"name\":\"extra\",\"type\":\"bytes\"}]}");
	public java.lang.CharSequence queue;
	public java.lang.CharSequence consumer;
	public boolean exclusive;
	public boolean autoack;
	public java.nio.ByteBuffer extra;

	public org.apache.avro.Schema getSchema() {
		return SCHEMA$;
	}

	// Used by DatumWriter. Applications should not call.
	public java.lang.Object get(int field$) {
		switch (field$) {
		case 0:
			return queue;
		case 1:
			return consumer;
		case 2:
			return exclusive;
		case 3:
			return autoack;
		case 4:
			return extra;
		default:
			throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}

	// Used by DatumReader. Applications should not call.
	@SuppressWarnings(value = "unchecked")
	public void put(int field$, java.lang.Object value$) {
		switch (field$) {
		case 0:
			queue = (java.lang.CharSequence) value$;
			break;
		case 1:
			consumer = (java.lang.CharSequence) value$;
			break;
		case 2:
			exclusive = (java.lang.Boolean) value$;
			break;
		case 3:
			autoack = (java.lang.Boolean) value$;
			break;
		case 4:
			extra = (java.nio.ByteBuffer) value$;
			break;
		default:
			throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}
}
