/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package mosaic.interop.idl.amqp;

@SuppressWarnings("all")
public class DeclareExchangeOperation extends
		org.apache.avro.specific.SpecificRecordBase implements
		org.apache.avro.specific.SpecificRecord {
	public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema
			.parse("{\"type\":\"record\",\"name\":\"DeclareExchangeOperation\",\"namespace\":\"mosaic.interop.idl.amqp\",\"fields\":[{\"name\":\"exchange\",\"type\":\"string\"},{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"ExchangeType\",\"symbols\":[\"DIRECT\",\"FANOUT\",\"TOPIC\"]}},{\"name\":\"durable\",\"type\":\"boolean\"},{\"name\":\"autodelete\",\"type\":\"boolean\"},{\"name\":\"passive\",\"type\":\"boolean\"}]}");
	public java.lang.CharSequence exchange;
	public mosaic.interop.idl.amqp.ExchangeType type;
	public boolean durable;
	public boolean autodelete;
	public boolean passive;

	public org.apache.avro.Schema getSchema() {
		return SCHEMA$;
	}

	// Used by DatumWriter. Applications should not call.
	public java.lang.Object get(int field$) {
		switch (field$) {
		case 0:
			return exchange;
		case 1:
			return type;
		case 2:
			return durable;
		case 3:
			return autodelete;
		case 4:
			return passive;
		default:
			throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}

	// Used by DatumReader. Applications should not call.
	@SuppressWarnings(value = "unchecked")
	public void put(int field$, java.lang.Object value$) {
		switch (field$) {
		case 0:
			exchange = (java.lang.CharSequence) value$;
			break;
		case 1:
			type = (mosaic.interop.idl.amqp.ExchangeType) value$;
			break;
		case 2:
			durable = (java.lang.Boolean) value$;
			break;
		case 3:
			autodelete = (java.lang.Boolean) value$;
			break;
		case 4:
			passive = (java.lang.Boolean) value$;
			break;
		default:
			throw new org.apache.avro.AvroRuntimeException("Bad index");
		}
	}
}
