/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package mosaic.interop.idl.amqp;

@SuppressWarnings("all")
public enum ExchangeType {
	DIRECT, FANOUT, TOPIC;
	public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema
			.parse("{\"type\":\"enum\",\"name\":\"ExchangeType\",\"namespace\":\"mosaic.interop.idl.amqp\",\"symbols\":[\"DIRECT\",\"FANOUT\",\"TOPIC\"]}");
}
